### PR TITLE
New charts

### PR DESCRIPTION
**Pull request by fmauNeko**
Hello again,
After adding the calendar, I thought "Why not add them all !".

So here it is, I added them all, sorted them alphabetically, and took away the trailing commas :)

### CODE REVIEW

**Comment by fmauNeko** [comment]
Apologies, I may have flooded travis a little, rebasing is hard.

**Comment by wesalvaro** [comment]
So, I forgot to point out in your other PR that you were missing a demo. =\
That's been the limiting factor on adding the chart types. You can check out #94 for one issue. It'd be good to have demos to access issues like the one mentioned for the annotation chart.
Potentially, thought, we could use a `dom-repeat` to create the demos?
What do you think?

**Comment by fmauNeko** [comment]
I think most of those charts require some specific data sets.
I'll work on some demos as soon as possible !

**Comment by wesalvaro** [comment]
Sorry! Thanks so much!

**Pull request closed without merging**
