### PR TITLE
Fix typo at google-chart.html

### PR DESCRIPTION
**Pull request by kienpham2000**

### CODE REVIEW

**Comment by kienpham2000** [comment]
I signed it!

**Comment by wesalvaro** [comment]
Hi!

Thanks for the typo fix. VIM-world problems. Ha.
Would you please update your commit message to something more descriptive than "update"?

Thanks,
Wes

**Comment by kienpham2000** [comment]
I just did the edit from Github UI. You suggest cloning this repo, rebase and force push a new commit?

**Comment by wesalvaro** [comment]
If you make the change locally, [amending your commit message](http://stackoverflow.com/a/179147/1142064), you can just do a force push.

**Comment by kienpham2000** [comment]
@wesalvaro done, lots of work for such a simple PR btw

**Comment by ebidel** [comment]
LGTM

**Comment by wesalvaro** [comment]
@kevinpschaaf Yeah, sorry about that, but it's always good to have a descriptive commit message.

Avoiding things like "update" or "changed" or "fixed" without more description is good practice.

Sorry and thanks!

**Pull request merged**
