### PR TITLE
feat(a11y): allow to show alternative content with the chart

### PR DESCRIPTION
**Pull request by felixzapata**
Hi, I propose this change, to allow the user to add some alternative content with the chart. This way, the user can access to some information about the chart. 

I think that a more complete feature would be that with the data you configure the component, it renders a table. For example, if you choose a pie, below the pie the component will generate a table with the information in the chart. 

Regards.

### CODE REVIEW

**Comment by ebidel** [comment]
If this is for a11y, I think it would be better to annotate the element with aria roles, labels, etc.

**Comment by felixzapata** [comment]
hi, yes it is for a11y. The problem is when [you have a graph (or another similar)](http://webaim.org/techniques/alttext/#complex) the goal is to keep the information accessible. 

But let me check first again because I think inside the Google charts, the original API creates alternative content. If it does, this pull request won´t be necessary.

Sorry.

**Comment by ebidel** [comment]
Yes, but I'm saying https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute and https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute might be more appropriate than insertion points. Insertion points are just a shadow dom rendering tool.

**Comment by felixzapata** [comment]
hi, my fault. This pull request is not necessary at this moment. The feature I proposed about a table it exists now in the current Google Charts API and it creates "hidden" alternative content with labels after the chart. However I think that it should be optional if this content is visible or not, but this is more of Google Charts that the Polymer component.

I will close the pull request.

Sorry.

**Pull request closed without merging**
