### PR TITLE
Polymer 3

### PR DESCRIPTION
**Pull request by rslawik**
Upgrade `<google-chart>` to Polymer 3 by running modulizer.

Steps: https://polymer-library.polymer-project.org/3.0/docs/upgrade

Tested:
- `polymer test --module-resolution=node --npm`
- `polymer serve --module-resolution=node --npm` and visiting demo page

### CODE REVIEW

**Comment by rslawik** [comment]
Hi @wesalvaro, could you have a look?

It is an alternative version of #222 but without the problematic `initializeOnce` function.

It contains various fixes to allow the code to be imported and compiled:

 - add `@license` to all js files required by policy
 - delete `@attribute` that is not a valid JSDoc tag
 - fixed JSDoc type annotations
 - inlined loader script URL to pass conformance checks

I also CC'ed you on the internal CL that imports the component as ES module.

Tested:

 - `polymer test --module-resolution=node --npm`
 - `polymer serve --module-resolution=node --npm` and visited demo page



@e111077: it would be great to publish it to npm once merged.

Thanks!

**Comment by wesalvaro** [comment]
Thanks!

**Comment by e111077** [comment]
published https://www.npmjs.com/@google-web-components/google-chart

**Comment by rslawik** [comment]
Great, thank you!
Small live demo: https://jsbin.com/taximobici/edit?html,output

**Pull request merged**
