### PR TITLE
Send google-chart.css as text/css instead of doc

### PR DESCRIPTION
**Pull request by kienpham2000**
Chrome is currently throws this warning:
Resource interpreted as Document but transferred with MIME type text/css: google-chart/google-chart.css"

### CODE REVIEW

**Comment by wesalvaro** [comment]
This is actually WAI. See [here](https://www.polymer-project.org/1.0/docs/devguide/styling#external-stylesheets). However, it's deprecated. So if you want to champion the update the fix is to now use [Style Modules](https://www.polymer-project.org/1.0/docs/devguide/styling#style-modules).

**Comment by kienpham2000** [comment]
@wesalvaro thanks for your suggestion, updated PR to use style module.

**Comment by kienpham2000** [comment]
updated, you can easily squash commit when you merge.

**Comment by wesalvaro** [comment]
Nice! I missed that update. Really glad they added that.

**Comment by kienpham2000** [comment]
oppsss I like that name too, updated.

**Comment by web-padawan** [comment]
@wesalvaro could you tag this change please?

**Comment by wesalvaro** [comment]
https://github.com/GoogleWebComponents/google-chart/releases/tag/1.1.2

**Pull request merged**
