### PR TITLE
Add default table chart styles.

### PR DESCRIPTION
**Pull request by philipwalton**

### CODE REVIEW

**Comment by moderndeveloperllc** [comment]
:+1:

**Comment by ebidel** [comment]
@philipwalton do you want to rebase this on top of the new 1.0 element?

**Comment by philipwalton** [comment]
@ebidel I rebased against master, but after doing that I noticed a few other problems.

First of all, gviz tables have changed since I originally wrote this, so I'll have to update a few things (no big deal). Second, and more importantly, I'm not sure this will easily work with shady DOM, unless you know something I don't.

The problem is shady DOM rewrites styles so every selector gets classed with the element name. In this case:

```css
/* This selector... */
.google-visualization-table td { }

/* ...gets re-written as this: */
.google-visualization-table.google-chart td.google-chart { }
```

This works great when Polymer knows about the elements in the shadow DOM, but when gviz adds elements dynamically, they don't get the class `google-chart`, so the selectors don't match.

We *could* add the class to all dynamically inserted elements after render, but that doesn't seem like the right approach to solving this problem.

Thoughts?

**Comment by ebidel** [comment]
If gviz is adding markup that needs to be styled later, try  `scopedSubtree`. Is that the case?

https://github.com/Polymer/polymer/issues/2299#issuecomment-133178981

**Comment by philipwalton** [comment]
That is the case. I'll check `scopedSubtree` out, thanks.

**Comment by philipwalton** [comment]
Thanks, `scopedSubtree` worked perfectly, and the demo renders nicely now.

**Comment by wesalvaro** [comment]
What am I missing? The table seems styled to me already. Is this PR obsolete?

**Comment by philipwalton** [comment]
@wesalvaro I think the reason you're seeing styles now is because shady DOM (unlike true shadow DOM) isn't preventing the styles dynamically added by gviz from styling the table.

In a true shadow DOM context, you'd need these added styles because the external styles would do nothing.

**Comment by rslawik** [comment]
Google Charts table is styled correctly now: https://jsbin.com/fobivusemi/edit?html,output

**Pull request closed without merging**
