### PR TITLE
Update google-chart-styles.html

### PR DESCRIPTION
**Pull request by Primerz**
Enabling custom background color

### CODE REVIEW

**Comment by Primerz** [comment]
I signed it!

**Comment by Primerz** [comment]
Eventually add
`#chartdiv svg g path:first-child {
    stroke: transparent !important;
}`
to remove chart colored value representation's white border color

**Comment by wesalvaro** [comment]
Sorry, I'm not understanding from this issue. What is this addressing?

**Comment by rslawik** [comment]
I believe the default background color (white) of the chart can be removed by passing the following options:
```javascript
{
  backgroundColor: 'transparent',
}
```
[JS bin demo](https://jsbin.com/gevukavulu/edit?html,output)

**Pull request closed without merging**
