### PR TITLE
Add Timeline support

### PR DESCRIPTION
**Pull request by steven-ferguson**
Since #62 looks dead, I created a new PR that is up to date with master.

### CODE REVIEW

**Comment by ebidel** [comment]
Thanks. Can you add a test?

**Comment by steven-ferguson** [comment]
As I was writing some tests I discovered that timelines will not currently work if you use ```cols``` and ```rows``` because ```dataTable.addRows``` does not support [the Google Date string representation](https://developers.google.com/chart/interactive/docs/datesandtimes#dates-and-times-using-the-date-string-representation).

Always using ```google.visualization.arrayToDataTable``` to create the dataTable could resolve this:

```javascript
data = [this.cols].concat(this.rows);
dataTable = google.visualization.arrayToDataTable(data);
```

**Comment by wesalvaro** [comment]
@steven-ferguson I think this is a problem that extends beyond just the Timeline chart; don't other charts accept Date formats?

**Comment by wesalvaro** [comment]
[Here is a jsbin](http://jsbin.com/mesetebafe/edit?js,console) that shows the different methods of creating a DataTable.

I wonder if there is any benefit is to using the builder... I think it should be changed.

**Comment by wesalvaro** [comment]
OK, after more investigation, the arrayToDataTable approach is, sadly, much slower. It has an entire extra stage of converting the rows to "JSON" and then just passes that to the constructor of `DataTable`. I'm looking into adding the same parsing functionality that is done in the `DataTable` constructor into the `addRows` method. I think this functionality was just overlooked.

**Comment by wesalvaro** [comment]
Another update... lol. I was able to make the change so that the Date String representation can be used with the builder approach. So, I think we should table this part of the issue for now until that is available.

**Comment by wesalvaro** [comment]
Thinking about it some more, I'm not fully convinced that the `addRows` etc methods should have this functionality. The `rows` and `cols` are not loaded by AJAX and this should only be a problem when statically specifying the attributes.

I've created PR #78 to get Timeline functionality added without support for this.

**Comment by steven-ferguson** [comment]
So do you have to setup the timeline using JS? It's not clear to me how to do this using only the webcomponent. JSBIN:  [http://jsbin.com/laweru/1/edit?html,output](http://jsbin.com/laweru/1/edit?html,output)

**Comment by wesalvaro** [comment]
@steven-ferguson Check out [the demo page](https://github.com/GoogleWebComponents/google-chart/blob/master/demo/index.html#L319) in the repo for an example. =)

**Pull request closed without merging**
