### PR TITLE
Corrected JsDoc type on google-chart-loader.html

### PR DESCRIPTION
**Pull request by JeanRemiDelteil**

### CODE REVIEW

**Comment by JeanRemiDelteil** [comment]
I signed it!

**Comment by wesalvaro** [comment]
Are you having issues with the annotations as they are?
These have been tested as working in compilation.
The set brackets `{}` are only needed for [more than one type](https://code.google.com/archive/p/jsdoc-toolkit/wikis/TagType.wiki) and I have never seen [a Closure type annotation](https://developers.google.com/closure/compiler/docs/js-for-compiler) `String`, it's always `string`.

The type `String` refers to a `new String('foo')` which is not the same as a `string` of `'foo'`.
```js
s = new String('foo')
  String {0: "f", 1: "o", 2: "o", length: 3, [[PrimitiveValue]]: "foo"}
t = 'foo'
  "foo"
s == t
  true
s === t
  false
u = 'foo'
  "foo"
t === u
  true
```
Polymer uses `type: String` because it needs to be valid JS, which `string` is not.

**Comment by JeanRemiDelteil** [comment]
My linting gives errors for type not wrapped in {}
For the 'String', if it's not necessary I can change it back ?

**Comment by wesalvaro** [comment]
OK, that sounds good. I'm not against adding the `{}`, I guess some linters are just pickier.

But please change the `String` back to `string`.

Thanks so much!

**Comment by wesalvaro** [comment]
Would you please fixup the commit and force push it?

**Comment by JeanRemiDelteil** [comment]
I'm not sure if I did the correct thing but it's all down to one commit now

**Comment by wesalvaro** [comment]
LGTM.

**Pull request merged**
