### PR TITLE
Use ChartWrapper to load/render charts.

### PR DESCRIPTION
**Pull request by wesalvaro**
This dumps a lot of code with no trade-off (hopefully).

It also loads the material chart libraries! _yay_

The only issue right now is that imageURIs are currently broken.

### CODE REVIEW

**Comment by wesalvaro** [comment]
R: @ebidel 
This PR is currently just a preview. It's not ready for a proper review.

**Comment by joekarasek** [comment]
I had issues getting google charts to load/render correctly on Safari and Firefox when the bower dependency was passed through gulp-vulcanize (I'm building a polymer app). My understanding (and I'm a junior developer) is that the polyfill for web components caused a race situation: google was 'undefined'. I patched the problem by adding an additional CDN call for google charts loader to the head of the page, but am now getting a warning about multiple calls for google loader.

It would be great if your wrapper took care of this problem. I have not had the same issue with other google web components.

**Comment by wesalvaro** [comment]
Yes, this is an issue specific to the visualization libraries. It's being worked on, but is not ready yet.

Sorry for the inconvenience, I'd love to see it fixed, too.

**Comment by wesalvaro** [comment]
@joekarasek Do you still have the same issue with the latest version (1.1.0) of the element?

**Comment by rslawik** [comment]
Migrated to `ChartWrapper` in #250.

**Pull request closed without merging**
