### PR TITLE
Removed a trailing coma

### PR DESCRIPTION
**Pull request by TemplarRei**
A trailing coma on line 8 was forcing making the json unparesable by the likes of bower. I know it's a terribly small change, but it's necessary for bower compatibility

### CODE REVIEW

**Comment by TemplarRei** [comment]
I signed it!

**Comment by wesalvaro** [comment]
Hey @TemplarRei, thanks for catching this!
I'm afraid that this update is still very much a work in progress; I haven't even tested Bower, yet.
I'm currently making so many heavy changes locally and doing force pushes after rebasing that this branch just isn't ready yet for PRs... It's definitely not guaranteed to be stable, even though that's what I'm going for. After finishing out the feature with the dashboard bindings (as well as writing and updating all the tests), I'll get it design and code reviewed so that we can start using and ironing the bugs out of it ASAP.
I'm glad you're testing it out, please let me know what you think!

**Comment by TemplarRei** [comment]
Thanks @wesalvaro! I'll test more and add things if/when I can. And I know it's the smalles change, so I only mentioned it because it breaks bower.

**Comment by wesalvaro** [comment]
No problem! I pushed the latest version with your comma. It should be feature complete, now. I just need to get tests added and reviewed before merging it back into the master.

**Pull request closed without merging**
